import type { Hono } from "hono";

/** Exhaustive retired HTTP surface. Reused canonical paths are excluded. */
export const RETIRED_CLI_ROUTES: Readonly<Record<string, string>> = {
  "GET /api/multiremi/chats/:id/sessions/:sessionId/events": "remi message list <conversation>",
  "POST /api/multiremi/chats/:id/sessions/:sessionId/messages": "remi message send <conversation>",
  "GET /api/multiremi/chats/:id/sessions/:sessionId/tasks": "remi turn list --session <conversation>",
  "POST /api/multiremi/chats/:id/sessions/:sessionId/tasks": "remi message send <conversation> --to <agent> --kind request",
  "DELETE /api/chat/sessions/:sessionId/queue": "remi message list <conversation> --unread-by <agent> 后逐条 remi message delete <message>",
  "DELETE /api/chat/sessions/:sessionId/queue/:taskId": "remi message delete <message>",
  "DELETE /api/comments/:id": "remi message delete <message>",
  "DELETE /api/comments/:id/reactions": "remi message react <message> --emoji <emoji> --remove",
  "DELETE /api/comments/:id/resolve": "remi message resolve <message> --no-resolved",
  "DELETE /api/multiremi/comments/:id": "remi message delete <message>",
  "DELETE /api/multiremi/comments/:id/reactions": "remi message react <message> --emoji <emoji> --remove",
  "DELETE /api/multiremi/comments/:id/resolve": "remi message resolve <message> --no-resolved",
  "GET /api/chat/pending-tasks": "remi message list <conversation> --unread-by <agent>",
  "GET /api/chat/sessions/:sessionId/pending-task": "remi message list <conversation> --unread-by <agent>",
  "GET /api/inbox/page": "remi inbox --limit <n> --cursor <cursor>",
  "GET /api/inbox/summary": "remi inbox",
  "GET /api/inbox/unread-count": "remi inbox",
  "GET /api/issues/:id/active-task": "remi turn list --issue <issue>",
  "GET /api/issues/:id/comments": "remi message list <conversation>",
  "GET /api/issues/:id/decisions": "remi issue question list <issue>",
  "GET /api/issues/:id/sessions/:sessionId/events": "remi message list <conversation>",
  "GET /api/issues/:id/sessions/:sessionId/tasks": "remi turn list --session <conversation>",
  "GET /api/issues/:id/task-runs": "remi turn list --issue <issue>",
  "GET /api/multiremi/chats/:id/messages": "remi message list <conversation>",
  "GET /api/multiremi/comments/:id/attachments": "remi message get <message>",
  "GET /api/multiremi/comments/:id/reactions": "remi message get <message>",
  "GET /api/multiremi/inbox": "remi inbox",
  "GET /api/multiremi/issues/:id/comments": "remi message list <conversation>",
  "GET /api/multiremi/tasks": "remi turn list",
  "GET /api/multiremi/tasks/:id": "remi turn get <turn>",
  "GET /api/multiremi/tasks/:id/human-requests": "remi inbox",
  "GET /api/multiremi/tasks/:id/inspection": "remi turn get <turn> --attempts",
  "GET /api/multiremi/tasks/:id/messages": "remi turn trace read <turn>",
  "GET /api/multiremi/tasks/:id/steer": "remi message list <conversation> --unread-by <agent>",
  "GET /api/tasks/:id/human-requests": "remi inbox",
  "GET /api/tasks/:id/inspection": "remi turn get <turn> --attempts",
  "GET /api/tasks/:id/steer": "remi message list <conversation> --unread-by <agent>",
  "GET /api/tasks/:id/trace": "remi turn trace read <turn>",
  "GET /api/tasks/:taskId/messages": "remi turn trace read <turn>",
  "GET /api/tasks/:taskId/prompt": "remi turn get <turn> --input",
  "PATCH /api/chat/sessions/:sessionId/queue/:taskId": "remi message edit <message>",
  "PATCH /api/multiremi/comments/:id": "remi message edit <message>",
  "POST /api/chat/attachments/send": "remi message send --attachment <path>",
  "POST /api/chat/sessions/:sessionId/messages": "remi message send <conversation>",
  "POST /api/chat/sessions/:sessionId/queue/:taskId/prioritize": "remi message delete <message> 后重新 remi message send <conversation>（按消息顺序）",
  "POST /api/chat/sessions/:sessionId/read": "remi inbox read <conversation>",
  "POST /api/comments/:id/reactions": "remi message react <message> --emoji <emoji>",
  "POST /api/comments/:id/resolve": "remi message resolve <message>",
  "POST /api/inbox/:id/archive": "remi inbox read <conversation>",
  "POST /api/inbox/archive-all": "remi inbox read-all",
  "POST /api/inbox/archive-all-read": "remi inbox read-all",
  "POST /api/inbox/archive-completed": "remi inbox read-all",
  "POST /api/inbox/mark-all-read": "remi inbox read-all",
  "POST /api/issues/:id/comments": "remi message send <conversation>",
  "POST /api/issues/:id/decisions": "原生 AskUserQuestion；先用 remi issue responsibility <issue> 查看责任归属",
  "POST /api/issues/:id/decisions/:decisionId/answer": "remi message question answer <question> --revision <route_revision> --data <json>",
  "POST /api/issues/:id/decisions/:decisionId/escalate": "remi message question escalate <question> --revision <route_revision> --reason <reason>",
  "POST /api/issues/:id/decisions/:decisionId/withdraw": "remi message question close <question> --revision <route_revision> --reason <reason>",
  "POST /api/issues/:id/rerun": "remi message send <issue> --to issue-owner --kind request",
  "POST /api/issues/:id/sessions/:sessionId/messages": "remi message send <conversation>",
  "POST /api/issues/:id/sessions/:sessionId/tasks": "remi message send <conversation> --to <agent> --kind request",
  "POST /api/issues/:id/tasks/:taskId/cancel": "remi turn cancel <turn>",
  "POST /api/multiremi/chats/:id/messages": "remi message send <conversation>",
  "POST /api/multiremi/comments/:id/reactions": "remi message react <message> --emoji <emoji>",
  "POST /api/multiremi/comments/:id/resolve": "remi message resolve <message>",
  "POST /api/multiremi/inbox/:id/archive": "remi inbox read <conversation>",
  "POST /api/multiremi/issues/:id/comments": "remi message send <conversation>",
  "POST /api/multiremi/tasks": "remi message send --to <agent> --kind request",
  "POST /api/multiremi/tasks/:id/cancel": "remi turn cancel <turn>",
  "POST /api/multiremi/tasks/:id/human-requests/:requestId/respond": "remi message question answer <question> --revision <route_revision> --data <json>",
  "POST /api/multiremi/tasks/:id/redispatch": "remi turn retry <turn> --cold",
  "POST /api/multiremi/tasks/:id/steer": "remi message send --to <agent> (收尾用 remi turn wrap-up <turn>)",
  "POST /api/tasks/:id/cancel": "remi turn cancel <turn>",
  "POST /api/tasks/:id/human-requests/:requestId/respond": "remi message question answer <question> --revision <route_revision> --data <json>",
  "POST /api/tasks/:id/redispatch": "remi turn retry <turn> --cold",
  "POST /api/tasks/:id/steer": "remi message send --to <agent> (收尾用 remi turn wrap-up <turn>)",
  "PUT /api/comments/:id": "remi message edit <message>",
  "PUT /api/multiremi/comments/:id": "remi message edit <message>",
  "POST /api/inbox/:id/read": "remi inbox read <conversation>",
  "POST /api/multiremi/inbox/:id/read": "remi inbox read <conversation>"
};

export function registerRetiredCliRoutes(app: Hono): void {
  for (const [route, replacement] of Object.entries(RETIRED_CLI_ROUTES)) {
    const separator = route.indexOf(" ");
    app.on(route.slice(0, separator), route.slice(separator + 1), (c) =>
      c.json({ code: "route_retired", replacement }, 410));
  }
}
