#!/usr/bin/env bun

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { cliCommandInventory } from "../apps/remi/cli/index.js";
import {
  cliCoverageReport,
  cliRuntimeCapabilities,
  type CliCapabilitiesManifest,
  type CliExemptCategory,
  type CliManifestRoute,
  validateCliCapabilities,
} from "./cli-capabilities.js";

const ROOT = resolve(import.meta.dir, "..");
const GOLDEN_PATH = resolve(ROOT, "scripts/api-routes.golden.json");
const MANIFEST_PATH = resolve(ROOT, "cli-capabilities.json");
const RUNTIME_MANIFEST_PATH = resolve(ROOT, "packages/server/src/api/cli-capabilities-generated.ts");
const MAX_PLANNED_ROUTES = 0;

const DOMAINS = [
  "context", "workspace", "member", "invite", "token",
  "project", "repo", "knowledge", "memory", "wiki",
  "issue", "comment", "session", "share", "label", "attachment",
  "chat", "task",
  "agent", "squad", "skill", "plugin",
  "runtime", "daemon", "autopilot", "scm", "messaging", "feishu",
  "inbox", "notification", "pin", "dashboard", "platform", "billing", "lark",
];

const DOMAIN_ALIASES: Record<string, string> = {
  "agent-plugins": "plugin",
  "agent-templates": "agent",
  "agent-activity-30d": "dashboard",
  "agent-run-counts": "dashboard",
  "agent-task-snapshot": "dashboard",
  "assignee-frequency": "dashboard",
  agents: "agent",
  attachments: "attachment",
  autopilots: "autopilot",
  chats: "chat",
  comments: "comment",
  daemons: "daemon",
  inbox: "inbox",
  invitations: "invite",
  issues: "issue",
  labels: "label",
  members: "member",
  pins: "pin",
  projects: "project",
  runtimes: "runtime",
  skills: "skill",
  squads: "squad",
  tasks: "task",
  tokens: "token",
  workspaces: "workspace",
  "notification-preferences": "notification",
  "cloud-billing": "billing",
  "cloud-runtime": "runtime",
  feedback: "platform",
  health: "platform",
  healthz: "platform",
  install: "lark",
  models: "runtime",
  "project-docs": "wiki",
  "project-knowledge": "memory",
  readyz: "platform",
  scheduler: "autopilot",
  shares: "share",
};

function main(): void {
  const golden = JSON.parse(readFileSync(GOLDEN_PATH, "utf8")) as { routes: string[] };
  const inventory = cliCommandInventory();
  const commands = Object.fromEntries(inventory.map((entry) => [entry.id, {
    command: `remi ${entry.path.join(" ")}`,
    aliases: entry.aliases.map((alias) => `remi ${alias.path.join(" ")}`),
    auth: [...entry.auth],
    capability: entry.capability,
    mutation: entry.mutation,
    output: [...entry.outputs],
    hidden: entry.hidden,
    ...(entry.id.startsWith("legacy.") ? { migration_status: "legacy_passthrough" as const } : { migration_status: "native" as const }),
    ...(entry.id === "legacy.multiremi" ? { internal: true } : {}),
  }]));
  const routes = Object.fromEntries(golden.routes.map((route) => [route, classifyRoute(route)]));
  const manifest: CliCapabilitiesManifest = {
    schema_version: 1,
    generated_from: "scripts/api-routes.golden.json",
    max_planned_routes: MAX_PLANNED_ROUTES,
    domains: DOMAINS,
    commands,
    aliases: {
      ...Object.fromEntries(inventory.flatMap((entry) => entry.aliases
        .filter((alias) => alias.deprecatedSince)
        .map((alias) => [`remi ${alias.path.join(" ")}`, {
          command: entry.id,
          deprecated_since: alias.deprecatedSince!,
          replacement: alias.replacement ?? `remi ${entry.path.join(" ")}`,
          hidden: Boolean(alias.hidden),
        }]))),
      "remi multiremi": {
        command: "legacy.multiremi",
        deprecated_since: "0.3.0",
        replacement: "remi <command>",
        hidden: true,
      },
    },
    routes,
  };
  const errors = validateCliCapabilities(golden.routes, manifest, inventory);
  if (errors.length) throw new Error(errors.join("\n"));
  writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`);
  const runtimeManifest = cliRuntimeCapabilities(manifest);
  writeFileSync(
    RUNTIME_MANIFEST_PATH,
    `// Generated by scripts/generate-cli-capabilities.ts. Do not edit manually.\n`
      + `export const CLI_CAPABILITIES_RUNTIME = ${JSON.stringify(runtimeManifest, null, 2)} as const;\n`,
  );
  const report = cliCoverageReport(manifest);
  console.log(`CLI capabilities: ${report.mapped} mapped / ${report.exempt} exempt / ${report.missing} missing (${report.total} routes)`);
}

function classifyRoute(route: string): CliManifestRoute {
  const mapped = mappedResourceCommand(route);
  if (mapped) return { command: mapped };
  const exempt = exemptRoute(route);
  if (exempt) return exempt;
  const { domain, command } = plannedCommand(route);
  return { planned_command: command, domain };
}

function mappedResourceCommand(route: string): string | null {
  const operation = mappedOperationsCommand(route);
  if (operation) return operation;
  const exact: Record<string, string> = {
    "GET /api/cli/context": "context.get",
    "GET /api/cli/capabilities": "context.get",
    "GET /api/workspaces": "workspace.list",
    "POST /api/workspaces": "workspace.create",
    "GET /api/invitations": "invite.list",
    "GET /api/me": "member.get",
    "PATCH /api/me": "member.update",
    "PATCH /api/me/onboarding": "member.onboarding.update",
    "POST /api/me/onboarding/complete": "member.onboarding.complete",
    "POST /api/me/onboarding/cloud-waitlist": "member.onboarding.cloud-waitlist",
    "POST /api/me/onboarding/runtime-bootstrap": "member.onboarding.runtime-bootstrap",
    "POST /api/me/onboarding/no-runtime-bootstrap": "member.onboarding.no-runtime-bootstrap",
    "GET /api/multiremi/members": "member.list",
    "POST /api/multiremi/members": "member.create",
    "GET /api/tokens": "token.list",
    "POST /api/tokens": "token.create",
    "POST /api/tokens/current/renew": "token.renew",
    "GET /api/multiremi/tokens": "token.list",
    "POST /api/multiremi/tokens": "token.create",
    "POST /api/cli-token": "token.create",
    "GET /api/projects": "project.list",
    "POST /api/projects": "project.create",
    "GET /api/projects/search": "project.search",
    "GET /api/multiremi/projects": "project.list",
    "POST /api/multiremi/projects": "project.create",
    "GET /api/multiremi/projects/search": "project.search",
    "GET /api/project-docs": "memory.list",
    "GET /api/knowledge/submissions": "knowledge.submissions",
    "GET /api/knowledge/submissions/:id": "knowledge.inspect",
    "POST /api/knowledge/submissions": "knowledge.submit",
    "GET /api/knowledge/runs": "knowledge.runs",
    "GET /api/knowledge/runs/:id": "knowledge.run.show",
    "POST /api/knowledge/migrate-legacy": "knowledge.migrate-legacy",
    "POST /api/projects/:id/knowledge/publish": "memory.publish",
    "POST /api/workspaces/:id/repos/:repositoryId/wiki/publish": "wiki.publish",
    "GET /api/project-knowledge/migration": "memory.migration.status",
    "POST /api/project-knowledge/migration/backfill": "memory.migration.backfill",
    "POST /api/project-knowledge/migration/verify": "memory.migration.verify",
    "POST /api/project-knowledge/migration/retry-failed": "memory.migration.retry",
    "GET /api/issues": "issue.list",
    "POST /api/issues": "issue.create",
    "GET /api/multiremi/issues": "issue.list",
    "POST /api/multiremi/issues": "issue.create",
    "GET /api/issues/grouped": "issue.grouped",
    "GET /api/multiremi/issues/grouped": "issue.grouped",
    "GET /api/issues/search": "issue.search",
    "GET /api/multiremi/issues/search": "issue.search",
    "GET /api/issues/children": "issue.children",
    "GET /api/multiremi/issues/children": "issue.children",
    "GET /api/issues/child-progress": "issue.child-progress",
    "GET /api/multiremi/issues/child-progress": "issue.child-progress",
    "POST /api/issues/batch-update": "issue.batch-update",
    "POST /api/multiremi/issues/batch-update": "issue.batch-update",
    "POST /api/issues/batch-delete": "issue.batch-delete",
    "POST /api/multiremi/issues/batch-delete": "issue.batch-delete",
    "POST /api/issues/quick-create": "issue.quick-create",
    "POST /api/multiremi/issues/quick-create": "issue.quick-create",
    "GET /api/labels": "label.list",
    "POST /api/labels": "label.create",
    "GET /api/multiremi/labels": "label.list",
    "POST /api/multiremi/labels": "label.create",
    "GET /api/chat/sessions": "chat.list",
    "POST /api/chat/sessions": "chat.create",
    "GET /api/chat/sessions/:sessionId/issue-updates": "chat.issue.updates.get",
    "PUT /api/chat/sessions/:sessionId/issue-updates": "chat.issue.updates.enable",
    "GET /api/chat/pending-tasks": "chat.pending",
    "GET /api/multiremi/chats": "chat.list",
    "POST /api/multiremi/chats": "chat.create",
    "GET /api/multiremi/tasks": "task.list",
    "POST /api/multiremi/tasks": "task.create",
    "POST /api/upload-file": "issue.attachment.upload",
    "POST /api/multiremi/attachments": "issue.attachment.upload",
    "GET /api/agents": "agent.list",
    "POST /api/agents": "agent.create",
    "GET /api/multiremi/agents": "agent.list",
    "POST /api/multiremi/agents": "agent.create",
    "POST /api/multiremi/agents/default": "agent.default",
    "GET /api/agent-templates": "agent.template.list",
    "GET /api/multiremi/agent-templates": "agent.template.list",
    "POST /api/agents/from-template": "agent.template.create",
    "POST /api/multiremi/agents/from-template": "agent.template.create",
    "GET /api/squads": "squad.list",
    "POST /api/squads": "squad.create",
    "GET /api/multiremi/squads": "squad.list",
    "POST /api/multiremi/squads": "squad.create",
    "GET /api/skills": "skill.list",
    "GET /api/skills/search": "skill.search",
    "POST /api/skills": "skill.create",
    "POST /api/skills/import": "skill.import",
    "GET /api/multiremi/skills": "skill.list",
    "GET /api/multiremi/skills/search": "skill.search",
    "POST /api/multiremi/skills": "skill.create",
    "POST /api/multiremi/skills/import": "skill.import",
    "GET /api/multiremi/agent-plugins": "plugin.list",
    "POST /api/multiremi/agent-plugins/inspect": "plugin.inspect",
    "POST /api/multiremi/agent-plugins/import": "plugin.import",
  };
  if (exact[route]) return exact[route]!;
  const rules: Array<[RegExp, string]> = [
    [/^GET \/api\/workspaces\/:id$/, "workspace.get"],
    [/^(?:PUT|PATCH) \/api\/workspaces\/:id$/, "workspace.update"],
    [/^DELETE \/api\/workspaces\/:id$/, "workspace.delete"],
    [/^POST \/api\/workspaces\/:id\/leave$/, "workspace.leave"],
    [/^GET \/api\/workspaces\/:id\/env$/, "workspace.env.get"],
    [/^PUT \/api\/workspaces\/:id\/env$/, "workspace.env.update"],
    [/^GET \/api\/workspaces\/:id\/organizer$/, "workspace.organizer.get"],
    [/^PUT \/api\/workspaces\/:id\/organizer$/, "workspace.organizer.update"],
    [/^GET \/api\/workspaces\/:id\/ssh-mesh$/, "workspace.ssh-mesh.get"],
    [/^PUT \/api\/workspaces\/:id\/ssh-mesh$/, "workspace.ssh-mesh.update"],
    [/^POST \/api\/workspaces\/:id\/ssh-mesh\/rotate$/, "workspace.ssh-mesh.rotate"],
    [/^POST \/api\/workspaces\/:id\/ssh-mesh\/test$/, "workspace.ssh-mesh.test"],
    [/^GET \/api\/workspaces\/:id\/relay-config$/, "workspace.relay.get"],
    [/^PUT \/api\/workspaces\/:id\/relay-config\/discovery$/, "workspace.relay.discovery"],
    [/^PUT \/api\/workspaces\/:id\/relay-config\/:engine$/, "workspace.relay.update"],
    [/^POST \/api\/workspaces\/:id\/relay-config\/:engine\/reveal$/, "workspace.relay.reveal"],
    [/^GET \/api\/workspaces\/:id\/bot-menu$/, "workspace.bot-menu.get"],
    [/^PUT \/api\/workspaces\/:id\/bot-menu$/, "workspace.bot-menu.update"],
    [/^POST \/api\/workspaces\/:id\/bot-menu\/publish$/, "workspace.bot-menu.publish"],
    [/^GET \/api\/workspaces\/:id\/bot-menu\/publish\/:requestId$/, "workspace.bot-menu.publish-status"],
    [/^GET \/api\/workspaces\/:id\/feishu-bot$/, "workspace.feishu-bot.get"],
    [/^PUT \/api\/workspaces\/:id\/feishu-bot$/, "workspace.feishu-bot.set"],
    [/^DELETE \/api\/workspaces\/:id\/feishu-bot$/, "workspace.feishu-bot.delete"],
    [/^GET \/api\/workspaces\/:id\/feishu-bot\/status$/, "workspace.feishu-bot.status"],
    [/^GET \/api\/workspaces\/:id\/feishu-bot\/candidates$/, "workspace.feishu-bot.candidates"],
    [/^GET \/api\/workspaces\/:id\/feishu-bot\/audit$/, "workspace.feishu-bot.audit"],
    [/^POST \/api\/workspaces\/:id\/feishu-bot\/test$/, "workspace.feishu-bot.test"],
    [/^POST \/api\/workspaces\/:id\/feishu-bot\/deploy$/, "workspace.feishu-bot.deploy"],
    [/^POST \/api\/workspaces\/:id\/feishu-bot\/stop$/, "workspace.feishu-bot.stop"],
    [/^POST \/api\/workspaces\/:id\/feishu-bot\/registration$/, "workspace.feishu-bot.register"],
    [/^GET \/api\/workspaces\/:id\/feishu-bot\/registration\/:sessionId$/, "workspace.feishu-bot.register-status"],
    [/^DELETE \/api\/workspaces\/:id\/feishu-bot\/registration\/:sessionId$/, "workspace.feishu-bot.register-cancel"],
    [/^GET \/api\/workspaces\/:id\/prompts$/, "workspace.prompt.get"],
    [/^GET \/api\/workspaces\/:id\/prompt-template$/, "workspace.prompt.template"],
    [/^PUT \/api\/workspaces\/:id\/prompts$/, "workspace.prompt.update"],
    [/^GET \/api\/workspaces\/:id\/issue-archive$/, "workspace.issue-archive.get"],
    [/^PUT \/api\/workspaces\/:id\/issue-archive$/, "workspace.issue-archive.update"],
    [/^GET \/api\/workspaces\/:id\/issue-topics$/, "workspace.issue-topics.get"],
    [/^PUT \/api\/workspaces\/:id\/issue-topics$/, "workspace.issue-topics.set"],
    [/^GET \/api\/workspaces\/:id\/runtime-provisions$/, "workspace.runtime-provision.list"],
    [/^POST \/api\/workspaces\/:id\/runtime-provisions$/, "workspace.runtime-provision.create"],
    [/^GET \/api\/workspaces\/:id\/runtime-provisions\/:provisionId$/, "workspace.runtime-provision.get"],
    [/^PATCH \/api\/workspaces\/:id\/runtime-provisions\/:provisionId$/, "workspace.runtime-provision.update"],
    [/^DELETE \/api\/workspaces\/:id\/runtime-provisions\/:provisionId$/, "workspace.runtime-provision.delete"],
    [/^GET \/api\/workspaces\/:id\/runtime-provisions\/:provisionId\/states$/, "workspace.runtime-provision.states"],
    [/^GET \/api\/workspaces\/:id\/members$/, "member.list"],
    [/^PATCH \/api\/workspaces\/:id\/members\/:memberId$/, "member.update"],
    [/^DELETE \/api\/workspaces\/:id\/members\/:memberId$/, "member.delete"],
    [/^POST \/api\/workspaces\/:id\/members$/, "invite.create"],
    [/^GET \/api\/multiremi\/members\/:id$/, "member.get"],
    [/^PATCH \/api\/multiremi\/members\/:id$/, "member.update"],
    [/^DELETE \/api\/multiremi\/members\/:id$/, "member.delete"],
    [/^GET \/api\/workspaces\/:id\/invitations$/, "invite.list"],
    [/^DELETE \/api\/workspaces\/:id\/invitations\/:invitationId$/, "invite.revoke"],
    [/^GET \/api\/invitations\/:id$/, "invite.get"],
    [/^POST \/api\/invitations\/:id\/accept$/, "invite.accept"],
    [/^POST \/api\/invitations\/:id\/decline$/, "invite.decline"],
    [/^DELETE \/api\/(?:multiremi\/)?tokens\/:id$/, "token.delete"],
    [/^GET \/api\/(?:multiremi\/)?projects\/:id$/, "project.get"],
    [/^(?:PUT|PATCH) \/api\/(?:multiremi\/)?projects\/:id$/, "project.update"],
    [/^DELETE \/api\/(?:multiremi\/)?projects\/:id$/, "project.archive"],
    [/^POST \/api\/(?:multiremi\/)?projects\/:id\/restore$/, "project.restore"],
    [/^GET \/api\/(?:multiremi\/)?projects\/:id\/resources$/, "project.resource.list"],
    [/^POST \/api\/(?:multiremi\/)?projects\/:id\/resources$/, "project.resource.create"],
    [/^(?:PUT|PATCH) \/api\/(?:multiremi\/)?projects\/:id\/resources\/:resourceId$/, "project.resource.update"],
    [/^DELETE \/api\/(?:multiremi\/)?projects\/:id\/resources\/:resourceId$/, "project.resource.delete"],
    [/^GET \/api\/(?:multiremi\/)?projects\/:id\/devices$/, "project.device.list"],
    [/^POST \/api\/(?:multiremi\/)?projects\/:id\/devices$/, "project.device.add"],
    [/^PUT \/api\/(?:multiremi\/)?projects\/:id\/devices$/, "project.device.set"],
    [/^DELETE \/api\/(?:multiremi\/)?projects\/:id\/devices\/:daemonId$/, "project.device.remove"],
    [/^GET \/api\/projects\/:id\/docs$/, "memory.list"],
    [/^POST \/api\/projects\/:id\/docs$/, "memory.create"],
    [/^GET \/api\/projects\/:id\/docs\/:ref$/, "memory.get"],
    [/^PUT \/api\/projects\/:id\/docs\/:ref$/, "memory.update"],
    [/^DELETE \/api\/projects\/:id\/docs\/:ref$/, "memory.delete"],
    [/^GET \/api\/projects\/:id\/docs\/:ref\/revisions$/, "wiki.revisions"],
    [/^GET \/api\/projects\/:id\/docs\/:ref\/backlinks$/, "memory.backlinks"],
    [/^GET \/api\/projects\/:id\/knowledge\/recall$/, "memory.search"],
    [/^GET \/api\/workspaces\/:id\/repos$/, "repo.list"],
    [/^POST \/api\/workspaces\/:id\/repos\/inspect$/, "repo.inspect"],
    [/^POST \/api\/workspaces\/:id\/repos$/, "repo.create"],
    [/^PATCH \/api\/workspaces\/:id\/repos\/:repositoryId$/, "repo.update"],
    [/^DELETE \/api\/workspaces\/:id\/repos\/:repositoryId$/, "repo.delete"],
    [/^GET \/api\/workspaces\/:id\/repository-wikis$/, "wiki.repository.list"],
    [/^GET \/api\/workspaces\/:id\/repos\/:repositoryId\/wiki$/, "wiki.repository.list"],
    [/^POST \/api\/workspaces\/:id\/repos\/:repositoryId\/wiki$/, "wiki.repository.create"],
    [/^POST \/api\/workspaces\/:id\/repos\/:repositoryId\/wiki\/batch$/, "wiki.push"],
    [/^POST \/api\/workspaces\/:id\/repos\/:repositoryId\/wiki\/build$/, "wiki.repository.build"],
    [/^GET \/api\/workspaces\/:id\/repos\/:repositoryId\/wiki\/:ref\/revisions$/, "wiki.repository.revisions"],
    [/^GET \/api\/workspaces\/:id\/repos\/:repositoryId\/wiki\/:ref\/backlinks$/, "wiki.repository.backlinks"],
    [/^GET \/api\/workspaces\/:id\/repos\/:repositoryId\/wiki\/:ref$/, "wiki.repository.get"],
    [/^PUT \/api\/workspaces\/:id\/repos\/:repositoryId\/wiki\/:ref$/, "wiki.repository.update"],
    [/^DELETE \/api\/workspaces\/:id\/repos\/:repositoryId\/wiki\/:ref$/, "wiki.repository.delete"],
    [/^GET \/api\/(?:multiremi\/)?issues\/:id$/, "issue.get"],
    [/^(?:PUT|PATCH) \/api\/(?:multiremi\/)?issues\/:id$/, "issue.update"],
    [/^DELETE \/api\/(?:multiremi\/)?issues\/:id$/, "issue.delete"],
    [/^POST \/api\/(?:multiremi\/)?issues\/:id\/restore$/, "issue.restore"],
    [/^POST \/api\/multiremi\/issues\/:id\/retitle$/, "issue.retitle"],
    [/^POST \/api\/multiremi\/issues\/:id\/assign$/, "issue.assign"],
    [/^GET \/api\/issues\/:id\/(?:generated-issues|children)$/, "issue.children"],
    [/^GET \/api\/multiremi\/issues\/:id\/children$/, "issue.children"],
    [/^GET \/api\/(?:multiremi\/)?issues\/:id\/timeline$/, "issue.timeline"],
    [/^GET \/api\/issues\/:id\/active-task$/, "issue.active-task"],
    [/^GET \/api\/issues\/:id\/task-runs$/, "issue.task-runs"],
    [/^GET \/api\/issues\/:id\/usage$/, "issue.usage"],
    [/^GET \/api\/issues\/:id\/workspace$/, "issue.workspace"],
    [/^POST \/api\/issues\/:id\/rerun$/, "issue.rerun"],
    [/^POST \/api\/issues\/:id\/tasks\/:taskId\/cancel$/, "issue.cancel"],
    [/^POST \/api\/issues\/:id\/squad-evaluated$/, "issue.squad-evaluated"],
    [/^GET \/api\/(?:multiremi\/)?issues\/:id\/dependencies$/, "issue.dependency.list"],
    [/^POST \/api\/(?:multiremi\/)?issues\/:id\/dependencies$/, "issue.dependency.add"],
    [/^DELETE \/api\/(?:multiremi\/)?issues\/:id\/dependencies\/:dependencyId$/, "issue.dependency.remove"],
    [/^GET \/api\/(?:multiremi\/)?issues\/:id\/reactions$/, "issue.reaction.list"],
    [/^POST \/api\/(?:multiremi\/)?issues\/:id\/reactions$/, "issue.reaction.add"],
    [/^DELETE \/api\/(?:multiremi\/)?issues\/:id\/reactions$/, "issue.reaction.remove"],
    [/^GET \/api\/(?:multiremi\/)?issues\/:id\/labels$/, "issue.label.list"],
    [/^POST \/api\/(?:multiremi\/)?issues\/:id\/labels$/, "issue.label.add"],
    [/^DELETE \/api\/(?:multiremi\/)?issues\/:id\/labels\/:labelId$/, "issue.label.remove"],
    [/^GET \/api\/(?:multiremi\/)?issues\/:id\/subscribers$/, "issue.subscriber.list"],
    [/^POST \/api\/multiremi\/issues\/:id\/subscribers$/, "issue.subscriber.add"],
    [/^POST \/api\/issues\/:id\/subscribe$/, "issue.subscriber.add"],
    [/^POST \/api\/issues\/:id\/unsubscribe$/, "issue.subscriber.remove"],
    [/^DELETE \/api\/multiremi\/issues\/:id\/subscribers\/:memberId$/, "issue.subscriber.remove"],
    [/^GET \/api\/(?:multiremi\/)?issues\/:id\/metadata$/, "issue.metadata.list"],
    [/^PUT \/api\/(?:multiremi\/)?issues\/:id\/metadata\/:key$/, "issue.metadata.set"],
    [/^DELETE \/api\/(?:multiremi\/)?issues\/:id\/metadata\/:key$/, "issue.metadata.delete"],
    [/^GET \/api\/(?:multiremi\/)?issues\/:id\/comments$/, "comment.list"],
    [/^POST \/api\/(?:multiremi\/)?issues\/:id\/comments$/, "comment.add"],
    [/^(?:PUT|PATCH) \/api\/(?:multiremi\/)?comments\/:id$/, "comment.update"],
    [/^DELETE \/api\/(?:multiremi\/)?comments\/:id$/, "comment.delete"],
    [/^POST \/api\/(?:multiremi\/)?comments\/:id\/resolve$/, "comment.resolve"],
    [/^DELETE \/api\/(?:multiremi\/)?comments\/:id\/resolve$/, "comment.unresolve"],
    [/^GET \/api\/multiremi\/comments\/:id\/reactions$/, "comment.reaction.list"],
    [/^POST \/api\/(?:multiremi\/)?comments\/:id\/reactions$/, "comment.reaction.add"],
    [/^DELETE \/api\/(?:multiremi\/)?comments\/:id\/reactions$/, "comment.reaction.remove"],
    [/^GET \/api\/multiremi\/comments\/:id\/attachments$/, "comment.attachment.list"],
    [/^GET \/api\/issues\/:id\/sessions$/, "session.list"],
    [/^POST \/api\/issues\/:id\/sessions$/, "session.create"],
    [/^GET \/api\/issues\/:id\/sessions\/:sessionId$/, "session.get"],
    [/^PATCH \/api\/issues\/:id\/sessions\/:sessionId$/, "session.update"],
    [/^GET \/api\/issues\/:id\/sessions\/:sessionId\/participants$/, "session.participant.list"],
    [/^POST \/api\/issues\/:id\/sessions\/:sessionId\/participants$/, "session.participant.add"],
    [/^DELETE \/api\/issues\/:id\/sessions\/:sessionId\/participants\/:participantType\/:participantId$/, "session.participant.remove"],
    [/^GET \/api\/issues\/:id\/sessions\/:sessionId\/events$/, "session.event.list"],
    [/^POST \/api\/issues\/:id\/sessions\/:sessionId\/messages$/, "session.message.create"],
    [/^GET \/api\/issues\/:id\/sessions\/:sessionId\/tasks$/, "session.task.list"],
    [/^POST \/api\/issues\/:id\/sessions\/:sessionId\/tasks$/, "session.task.create"],
    [/^GET \/api\/issues\/:id\/session-results$/, "session.result.list"],
    [/^POST \/api\/issues\/:id\/sessions\/:sessionId\/results$/, "session.result.publish"],
    [/^GET \/api\/issues\/:issueId\/session-archives$/, "session.archive.list"],
    [/^POST \/api\/issues\/:issueId\/session-archives\/:archiveId\/verify$/, "session.archive.verify"],
    [/^POST \/api\/issues\/:issueId\/session-archives\/:archiveId\/retry$/, "session.archive.retry"],
    [/^GET \/api\/workspaces\/:id\/session-archive$/, "session.config.get"],
    [/^PUT \/api\/workspaces\/:id\/session-archive$/, "session.config.update"],
    [/^GET \/api\/issues\/:id\/share$/, "share.get"],
    [/^POST \/api\/issues\/:id\/share$/, "share.create"],
    [/^POST \/api\/issues\/:id\/share\/extend$/, "share.extend"],
    [/^DELETE \/api\/issues\/:id\/share$/, "share.delete"],
    [/^GET \/api\/shares\/:token$/, "share.view"],
    [/^GET \/api\/shares\/:token\/attachments\/:attachmentId\/content$/, "share.view"],
    [/^GET \/api\/(?:multiremi\/)?labels\/:id$/, "label.get"],
    [/^(?:PUT|PATCH) \/api\/(?:multiremi\/)?labels\/:id$/, "label.update"],
    [/^DELETE \/api\/(?:multiremi\/)?labels\/:id$/, "label.delete"],
    [/^GET \/api\/(?:multiremi\/)?attachments\/:id$/, "issue.attachment.get"],
    [/^GET \/api\/attachments\/:id\/(?:content|download)$/, "issue.attachment.download"],
    [/^DELETE \/api\/attachments\/:id$/, "issue.attachment.delete"],
    [/^GET \/api\/(?:multiremi\/)?issues\/:id\/attachments$/, "issue.attachment.list"],
    [/^POST \/api\/multiremi\/issues\/:id\/attachments$/, "issue.attachment.upload"],
    [/^GET \/api\/multiremi\/chats\/:id$/, "chat.get"],
    [/^GET \/api\/chat\/sessions\/:sessionId$/, "chat.get"],
    [/^PATCH \/api\/multiremi\/chats\/:id$/, "chat.update"],
    [/^PATCH \/api\/chat\/sessions\/:sessionId$/, "chat.update"],
    [/^DELETE \/api\/chat\/sessions\/:sessionId$/, "chat.delete"],
    [/^GET \/api\/(?:multiremi\/chats\/:id|chat\/sessions\/:sessionId)\/messages$/, "chat.message.list"],
    [/^GET \/api\/chat\/sessions\/:sessionId\/messages\/page$/, "chat.message.list"],
    [/^POST \/api\/(?:multiremi\/chats\/:id|chat\/sessions\/:sessionId)\/messages$/, "chat.message.create"],
    [/^GET \/api\/chat\/sessions\/:sessionId\/pending-task$/, "chat.pending"],
    [/^POST \/api\/chat\/sessions\/:sessionId\/read$/, "chat.read"],
    [/^GET \/api\/multiremi\/tasks\/:id$/, "task.get"],
    [/^POST \/api\/multiremi\/tasks\/:id\/cancel$/, "task.cancel"],
    [/^POST \/api\/tasks\/:id\/cancel$/, "task.cancel"],
    [/^POST \/api\/(?:multiremi\/)?tasks\/:id\/redispatch$/, "task.redispatch"],
    [/^POST \/api\/(?:multiremi\/)?tasks\/:id\/steer$/, "task.steer"],
    [/^GET \/api\/(?:multiremi\/)?tasks\/:id\/steer$/, "task.steer.list"],
    [/^GET \/api\/(?:multiremi\/)?tasks\/:id\/inspection$/, "task.inspect"],
    [/^GET \/api\/(?:multiremi\/tasks\/:id|tasks\/:taskId)\/messages$/, "task.message.list"],
    [/^GET \/api\/tasks\/:taskId\/prompt$/, "task.prompt"],
    [/^GET \/api\/(?:multiremi\/)?tasks\/:id\/human-requests$/, "task.request.list"],
    [/^POST \/api\/(?:multiremi\/)?tasks\/:id\/human-requests\/:requestId\/respond$/, "task.request.respond"],
    [/^GET \/api\/(?:multiremi\/)?agents\/:id$/, "agent.get"],
    [/^(?:PUT|PATCH) \/api\/(?:multiremi\/)?agents\/:id$/, "agent.update"],
    [/^PUT \/api\/agents\/:id\/role$/, "agent.role.set"],
    [/^PUT \/api\/agents\/:id\/supervisor$/, "agent.supervisor.set"],
    [/^DELETE \/api\/multiremi\/agents\/:id$/, "agent.archive"],
    [/^POST \/api\/agents\/:id\/archive$/, "agent.archive"],
    [/^POST \/api\/agents\/:id\/restore$/, "agent.restore"],
    [/^POST \/api\/agents\/:id\/cancel-tasks$/, "agent.cancel-tasks"],
    [/^GET \/api\/(?:multiremi\/)?agent-templates\/:slug$/, "agent.template.get"],
    [/^GET \/api\/(?:multiremi\/)?agents\/:id\/skills$/, "agent.skill.list"],
    [/^PUT \/api\/(?:multiremi\/)?agents\/:id\/skills$/, "agent.skill.set"],
    [/^POST \/api\/agents\/:id\/skills\/add$/, "agent.skill.add"],
    [/^GET \/api\/(?:multiremi\/)?agents\/:id\/tasks$/, "agent.task.list"],
    [/^GET \/api\/agents\/:id\/env$/, "agent.env.get"],
    [/^PUT \/api\/agents\/:id\/env$/, "agent.env.update"],
    [/^GET \/api\/multiremi\/agents\/:id\/plugins$/, "agent.plugin.list"],
    [/^POST \/api\/multiremi\/agents\/:id\/plugins$/, "agent.plugin.bind"],
    [/^PATCH \/api\/multiremi\/agents\/:id\/plugins\/:bindingId$/, "agent.plugin.update"],
    [/^DELETE \/api\/multiremi\/agents\/:id\/plugins\/:bindingId$/, "agent.plugin.unbind"],
    [/^GET \/api\/(?:multiremi\/)?squads\/:id$/, "squad.get"],
    [/^(?:PUT|PATCH) \/api\/(?:multiremi\/)?squads\/:id$/, "squad.update"],
    [/^DELETE \/api\/(?:multiremi\/)?squads\/:id$/, "squad.archive"],
    [/^GET \/api\/(?:multiremi\/)?squads\/:id\/members$/, "squad.member.list"],
    [/^GET \/api\/squads\/:id\/members\/status$/, "squad.member.status"],
    [/^POST \/api\/(?:multiremi\/)?squads\/:id\/members$/, "squad.member.add"],
    [/^PATCH \/api\/(?:multiremi\/squads\/:id\/members|squads\/:id\/members\/role)$/, "squad.member.update"],
    [/^DELETE \/api\/(?:multiremi\/)?squads\/:id\/members$/, "squad.member.remove"],
    [/^GET \/api\/(?:multiremi\/)?skills\/:id$/, "skill.get"],
    [/^(?:PUT|PATCH) \/api\/(?:multiremi\/)?skills\/:id$/, "skill.update"],
    [/^DELETE \/api\/(?:multiremi\/)?skills\/:id$/, "skill.archive"],
    [/^GET \/api\/skills\/:id\/files$/, "skill.file.list"],
    [/^PUT \/api\/skills\/:id\/files$/, "skill.file.update"],
    [/^DELETE \/api\/skills\/:id\/files\/:fileId$/, "skill.file.delete"],
    [/^GET \/api\/multiremi\/agent-plugins\/:id$/, "plugin.get"],
    [/^PATCH \/api\/multiremi\/agent-plugins\/:id$/, "plugin.update"],
    [/^DELETE \/api\/multiremi\/agent-plugins\/:id$/, "plugin.archive"],
    [/^POST \/api\/multiremi\/agent-plugins\/:id\/restore$/, "plugin.restore"],
    [/^GET \/api\/multiremi\/agent-plugins\/:id\/versions$/, "plugin.version.list"],
    [/^POST \/api\/multiremi\/agent-plugins\/:id\/versions$/, "plugin.version.create"],
    [/^POST \/api\/multiremi\/agent-plugins\/:id\/activate$/, "plugin.activate"],
    [/^POST \/api\/multiremi\/agent-plugins\/:id\/rollback$/, "plugin.rollback"],
    [/^GET \/api\/multiremi\/agent-plugins\/:id\/runtimes$/, "plugin.runtime.list"],
    [/^POST \/api\/multiremi\/agent-plugins\/:id\/runtimes\/retry$/, "plugin.runtime.retry"],
    [/^GET \/api\/multiremi\/runtimes\/:runtimeId\/agent-plugins$/, "plugin.runtime.get"],
  ];
  return rules.find(([pattern]) => pattern.test(route))?.[1] ?? null;
}

function mappedOperationsCommand(route: string): string | null {
  const exact: Record<string, string> = {
    "GET /api/runtimes": "runtime.list",
    "GET /api/multiremi/runtimes": "runtime.list",
    "POST /api/multiremi/runtimes": "runtime.create",
    "GET /api/models": "runtime.model.catalog",
    "GET /api/multiremi/models": "runtime.model.catalog",
    "GET /api/cloud-runtime": "runtime.cloud.status",
    "GET /api/cloud-runtime/healthz": "runtime.cloud.health",
    "GET /api/cloud-runtime/readyz": "runtime.cloud.ready",
    "GET /api/cloud-runtime/nodes": "runtime.cloud.node.list",
    "POST /api/cloud-runtime/nodes": "runtime.cloud.node.create",
    "DELETE /api/cloud-runtime/nodes": "runtime.cloud.node.delete",
    "POST /api/cloud-runtime/nodes/start": "runtime.cloud.node.start",
    "POST /api/cloud-runtime/nodes/stop": "runtime.cloud.node.stop",
    "POST /api/cloud-runtime/nodes/reboot": "runtime.cloud.node.reboot",
    "POST /api/cloud-runtime/nodes/status": "runtime.cloud.node.status",
    "POST /api/cloud-runtime/nodes/exec": "runtime.cloud.node.exec",
    "GET /api/multiremi/daemons": "daemon.list",
    "GET /api/multiremi/scheduler": "autopilot.scheduler",
    "GET /api/autopilots": "autopilot.list",
    "GET /api/multiremi/autopilots": "autopilot.list",
    "POST /api/autopilots": "autopilot.create",
    "POST /api/multiremi/autopilots": "autopilot.create",
    "GET /api/scm/capabilities": "scm.capabilities",
    "GET /api/inbox": "inbox.list",
    "GET /api/multiremi/inbox": "inbox.list",
    "GET /api/inbox/page": "inbox.page",
    "GET /api/inbox/summary": "inbox.summary",
    "GET /api/inbox/unread-count": "inbox.unread-count",
    "POST /api/inbox/mark-all-read": "inbox.mark-all-read",
    "POST /api/inbox/archive-all": "inbox.archive-all",
    "POST /api/inbox/archive-all-read": "inbox.archive-all-read",
    "POST /api/inbox/archive-completed": "inbox.archive-completed",
    "GET /api/notification-preferences": "notification.get",
    "GET /api/multiremi/notification-preferences": "notification.get",
    "PUT /api/notification-preferences": "notification.update",
    "PUT /api/multiremi/notification-preferences": "notification.update",
    "GET /api/multiremi/notification-channels": "notification.channel.list",
    "POST /api/multiremi/notification-channels": "notification.channel.create",
    "PATCH /api/multiremi/notification-channels/:id": "notification.channel.update",
    "DELETE /api/multiremi/notification-channels/:id": "notification.channel.delete",
    "GET /api/multiremi/notification-deliveries": "notification.delivery.list",
    "POST /api/multiremi/notification-deliveries/:id/retry": "notification.delivery.retry",
    "GET /api/pins": "pin.list",
    "GET /api/multiremi/pins": "pin.list",
    "POST /api/pins": "pin.create",
    "POST /api/multiremi/pins": "pin.create",
    "PUT /api/pins/reorder": "pin.reorder",
    "PUT /api/multiremi/pins/reorder": "pin.reorder",
    "GET /api/dashboard/usage/daily": "dashboard.usage.daily",
    "GET /api/dashboard/usage/by-agent": "dashboard.usage.by-agent",
    "GET /api/dashboard/runtime/daily": "dashboard.runtime.daily",
    "GET /api/dashboard/agent-runtime": "dashboard.agent-runtime",
    "GET /api/agent-activity-30d": "dashboard.agent-activity",
    "GET /api/multiremi/agent-activity-30d": "dashboard.agent-activity",
    "GET /api/agent-run-counts": "dashboard.agent-runs",
    "GET /api/multiremi/agent-run-counts": "dashboard.agent-runs",
    "GET /api/agent-task-snapshot": "dashboard.agent-tasks",
    "GET /api/multiremi/agent-task-snapshot": "dashboard.agent-tasks",
    "GET /api/assignee-frequency": "dashboard.assignee-frequency",
    "GET /api/multiremi/assignee-frequency": "dashboard.assignee-frequency",
    "GET /health": "platform.health",
    "GET /healthz": "platform.health",
    "GET /readyz": "platform.ready",
    "GET /health/realtime": "platform.realtime",
    "GET /api/multiremi/health": "platform.health",
    "GET /api/multiremi/platform/config": "platform.config",
    "GET /api/multiremi/platform/status": "platform.status",
    "GET /api/multiremi/platform/operations": "platform.operation.list",
    "POST /api/multiremi/platform/operations": "platform.operation.create",
    "POST /api/multiremi/platform/operations/:id/cancel": "platform.operation.cancel",
    "PATCH /api/multiremi/platform/settings": "platform.settings.update",
    "GET /api/multiremi/feedback": "platform.feedback.list",
    "POST /api/multiremi/feedback": "platform.feedback.create",
    "POST /api/feedback": "platform.feedback.create",
    "GET /api/remi/releases/latest/version": "platform.release.version",
    "GET /api/cloud-billing/balance": "billing.balance",
    "GET /api/cloud-billing/transactions": "billing.transaction.list",
    "GET /api/cloud-billing/batches": "billing.batch.list",
    "GET /api/cloud-billing/topups": "billing.topup.list",
    "GET /api/cloud-billing/price-tiers": "billing.tier.list",
    "POST /api/cloud-billing/checkout-sessions": "billing.checkout.create",
    "POST /api/cloud-billing/portal-sessions": "billing.portal.create",
    "POST /api/lark/binding/redeem": "lark.binding.redeem",
    "POST /api/multiremi/install/daemon": "lark.daemon.install",
    "GET /api/multiremi/install/daemon": "lark.daemon.status",
    "GET /auth/lark/url": "context.auth.lark",
    "POST /auth/google": "context.auth.google",
    "POST /auth/send-code": "context.auth.send-code",
    "POST /auth/verify-code": "context.auth.verify-code",
    "POST /auth/password": "context.auth.password",
    "POST /api/auth/password-accounts": "context.auth.password-account.set",
    "POST /auth/logout": "context.auth.logout",
  };
  if (exact[route]) return exact[route]!;
  const rules: Array<[RegExp, string]> = [
    [/^GET \/api\/(?:multiremi\/)?runtimes\/:id$/, "runtime.get"],
    [/^PATCH \/api\/(?:multiremi\/)?runtimes\/:id$/, "runtime.update"],
    [/^DELETE \/api\/runtimes\/:id$/, "runtime.delete"],
    [/^POST \/api\/runtimes\/:id\/archive-agents-and-delete$/, "runtime.archive-agents-and-delete"],
    [/^GET \/api\/(?:multiremi\/)?runtimes\/:id\/models$/, "runtime.model.list"],
    [/^PUT \/api\/(?:multiremi\/)?runtimes\/:id\/models$/, "runtime.model.set"],
    [/^POST \/api\/(?:multiremi\/)?runtimes\/:id\/models$/, "runtime.model.refresh"],
    [/^GET \/api\/(?:multiremi\/)?runtimes\/:id\/models\/:requestId$/, "runtime.model.status"],
    [/^POST \/api\/(?:multiremi\/)?runtimes\/:id\/update$/, "runtime.release.start"],
    [/^GET \/api\/(?:multiremi\/)?runtimes\/:id\/update\/:updateId$/, "runtime.release.status"],
    [/^POST \/api\/runtimes\/:id\/commands$/, "runtime.command.run"],
    [/^GET \/api\/runtimes\/:id\/commands\/:requestId$/, "runtime.command.run"],
    [/^POST \/api\/(?:multiremi\/)?runtimes\/:id\/local-skills$/, "runtime.skill.scan"],
    [/^GET \/api\/(?:multiremi\/)?runtimes\/:id\/local-skills\/:requestId$/, "runtime.skill.status"],
    [/^POST \/api\/(?:multiremi\/)?runtimes\/:id\/local-skills\/import$/, "runtime.skill.import"],
    [/^GET \/api\/(?:multiremi\/)?runtimes\/:id\/local-skills\/import\/:requestId$/, "runtime.skill.import-status"],
    [/^POST \/api\/(?:multiremi\/)?runtimes\/:id\/directory-scans$/, "runtime.directory.scan"],
    [/^GET \/api\/(?:multiremi\/)?runtimes\/:id\/directory-scans\/:requestId$/, "runtime.directory.status"],
    [/^GET \/api\/(?:multiremi\/)?runtimes\/:id\/usage$/, "runtime.usage"],
    [/^GET \/api\/(?:multiremi\/)?runtimes\/:id\/usage\/by-agent$/, "runtime.usage.by-agent"],
    [/^GET \/api\/(?:multiremi\/)?runtimes\/:id\/usage\/by-hour$/, "runtime.usage.by-hour"],
    [/^GET \/api\/(?:multiremi\/)?runtimes\/:id\/task-activity$/, "runtime.task-activity"],
    [/^GET \/api\/runtimes\/:id\/activity$/, "runtime.activity"],
    [/^GET \/api\/multiremi\/daemons\/:daemonId\/retirement-plan$/, "daemon.retirement-plan"],
    [/^POST \/api\/multiremi\/daemons\/:daemonId\/retire$/, "daemon.retire"],
    [/^GET \/api\/daemons\/:daemonId$/, "daemon.get"],
    [/^PATCH \/api\/daemons\/:daemonId$/, "daemon.dedicated.set"],
    [/^GET \/api\/(?:multiremi\/)?autopilots\/:id$/, "autopilot.get"],
    [/^PATCH \/api\/(?:multiremi\/)?autopilots\/:id$/, "autopilot.update"],
    [/^DELETE \/api\/(?:multiremi\/)?autopilots\/:id$/, "autopilot.delete"],
    [/^GET \/api\/(?:multiremi\/)?autopilots\/:id\/runs$/, "autopilot.run.list"],
    [/^GET \/api\/autopilots\/:id\/runs\/:runId$/, "autopilot.run.get"],
    [/^POST \/api\/(?:multiremi\/)?autopilots\/:id\/(?:run|trigger)$/, "autopilot.run"],
    [/^GET \/api\/(?:multiremi\/)?autopilots\/:id\/deliveries$/, "autopilot.delivery.list"],
    [/^GET \/api\/(?:multiremi\/)?autopilots\/:id\/deliveries\/:deliveryId$/, "autopilot.delivery.get"],
    [/^POST \/api\/(?:multiremi\/)?autopilots\/:id\/deliveries\/:deliveryId\/replay$/, "autopilot.delivery.replay"],
    [/^POST \/api\/autopilots\/:id\/triggers$/, "autopilot.trigger.create"],
    [/^PATCH \/api\/autopilots\/:id\/triggers\/:triggerId$/, "autopilot.trigger.update"],
    [/^DELETE \/api\/autopilots\/:id\/triggers\/:triggerId$/, "autopilot.trigger.delete"],
    [/^POST \/api\/autopilots\/:id\/triggers\/:triggerId\/rotate-webhook-token$/, "autopilot.trigger.rotate-token"],
    [/^PUT \/api\/autopilots\/:id\/triggers\/:triggerId\/signing-secret$/, "autopilot.trigger.set-secret"],
    [/^GET \/api\/workspaces\/:workspaceId\/scm\/connections$/, "scm.connection.list"],
    [/^POST \/api\/workspaces\/:workspaceId\/scm\/connections$/, "scm.connection.create"],
    [/^GET \/api\/workspaces\/:workspaceId\/scm\/connections\/:connectionId$/, "scm.connection.get"],
    [/^PATCH \/api\/workspaces\/:workspaceId\/scm\/connections\/:connectionId$/, "scm.connection.update"],
    [/^DELETE \/api\/workspaces\/:workspaceId\/scm\/connections\/:connectionId$/, "scm.connection.delete"],
    [/^POST \/api\/workspaces\/:workspaceId\/scm\/connections\/:connectionId\/verify$/, "scm.connection.verify"],
    [/^PUT \/api\/workspaces\/:workspaceId\/scm\/connections\/:connectionId\/repositories\/:repositoryId$/, "scm.repository.bind"],
    [/^DELETE \/api\/workspaces\/:workspaceId\/scm\/connections\/:connectionId\/repositories\/:repositoryId$/, "scm.repository.unbind"],
    [/^GET \/api\/workspaces\/:workspaceId\/scm\/events$/, "scm.event.list"],
    [/^GET \/api\/workspaces\/:workspaceId\/scm\/events\/:eventId$/, "scm.event.get"],
    [/^GET \/api\/workspaces\/:workspaceId\/messaging\/providers$/, "messaging.provider.list"],
    [/^GET \/api\/workspaces\/:workspaceId\/messaging\/connections$/, "messaging.connection.list"],
    [/^POST \/api\/workspaces\/:workspaceId\/messaging\/connections$/, "messaging.connection.add"],
    [/^GET \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId$/, "messaging.connection.get"],
    [/^POST \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId\/authorization-sessions$/, "messaging.connection.authorization.start"],
    [/^GET \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId\/authorization-sessions\/:sessionId$/, "messaging.connection.authorization.get"],
    [/^PATCH \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId$/, "messaging.connection.update"],
    [/^DELETE \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId$/, "messaging.connection.delete"],
    [/^POST \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId\/check$/, "messaging.connection.check"],
    [/^GET \/api\/workspaces\/:workspaceId\/messaging\/sources$/, "messaging.source.list"],
    [/^POST \/api\/workspaces\/:workspaceId\/messaging\/sources$/, "messaging.source.add"],
    [/^GET \/api\/workspaces\/:workspaceId\/messaging\/sources\/:sourceId$/, "messaging.source.get"],
    [/^PATCH \/api\/workspaces\/:workspaceId\/messaging\/sources\/:sourceId$/, "messaging.source.update"],
    [/^DELETE \/api\/workspaces\/:workspaceId\/messaging\/sources\/:sourceId$/, "messaging.source.delete"],
    [/^GET \/api\/workspaces\/:workspaceId\/messaging\/sources\/:sourceId\/status$/, "messaging.source.status"],
    [
      /^GET \/api\/workspaces\/:workspaceId\/messaging\/sources\/:sourceId\/available-conversations$/,
      "messaging.source.available-conversations",
    ],
    [/^GET \/api\/workspaces\/:workspaceId\/messaging\/conversations$/, "messaging.conversation.list"],
    [/^GET \/api\/workspaces\/:workspaceId\/messaging\/messages$/, "messaging.message.list"],
    [
      /^GET \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId\/messages\/:externalMessageId$/,
      "messaging.message.get",
    ],
    [
      /^POST \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId\/messages\/:externalMessageId\/resolve$/,
      "messaging.message.resolve",
    ],
    [
      /^POST \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId\/messages\/:externalMessageId\/notify$/,
      "messaging.message.notify",
    ],
    [
      /^POST \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId\/messages\/:externalMessageId\/draft-reply$/,
      "messaging.message.draft-reply",
    ],
    [
      /^POST \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId\/messages\/:externalMessageId\/propose-issue$/,
      "messaging.message.propose-issue",
    ],
    [
      /^POST \/api\/workspaces\/:workspaceId\/messaging\/connections\/:connectionId\/messages\/:externalMessageId\/create-issue$/,
      "messaging.message.create-issue",
    ],
    [/^GET \/api\/workspaces\/:workspaceId\/messaging\/proposals$/, "messaging.proposal.list"],
    [/^POST \/api\/workspaces\/:workspaceId\/messaging\/proposals\/:proposalId\/approve$/, "messaging.proposal.approve"],
    [/^POST \/api\/workspaces\/:workspaceId\/messaging\/proposals\/:proposalId\/reject$/, "messaging.proposal.reject"],
    [/^GET \/api\/workspaces\/:workspaceId\/feishu\/sources$/, "feishu.source.list"],
    [/^POST \/api\/workspaces\/:workspaceId\/feishu\/sources$/, "feishu.source.add"],
    [/^GET \/api\/workspaces\/:workspaceId\/feishu\/sources\/:sourceId$/, "feishu.source.get"],
    [/^GET \/api\/workspaces\/:workspaceId\/feishu\/sources\/:sourceId\/status$/, "feishu.source.status"],
    [/^PATCH \/api\/workspaces\/:workspaceId\/feishu\/sources\/:sourceId$/, "feishu.source.update"],
    [/^DELETE \/api\/workspaces\/:workspaceId\/feishu\/sources\/:sourceId$/, "feishu.source.delete"],
    [/^GET \/api\/workspaces\/:workspaceId\/feishu\/sources\/:sourceId\/available-chats$/, "feishu.source.available-chats"],
    [/^GET \/api\/workspaces\/:workspaceId\/feishu\/endpoints$/, "feishu.endpoint.list"],
    [/^POST \/api\/workspaces\/:workspaceId\/feishu\/endpoints\/:name\/check$/, "feishu.endpoint.check"],
    [/^GET \/api\/workspaces\/:workspaceId\/feishu\/chats$/, "feishu.chats.list"],
    [/^GET \/api\/workspaces\/:workspaceId\/feishu\/proposals$/, "feishu.proposals.list"],
    [/^GET \/api\/workspaces\/:workspaceId\/feishu\/messages$/, "feishu.messages.list"],
    [/^POST \/api\/workspaces\/:workspaceId\/feishu\/messages\/:messageId\/resolve$/, "feishu.messages.resolve"],
    [/^POST \/api\/workspaces\/:workspaceId\/feishu\/messages\/:messageId\/notify$/, "feishu.messages.notify"],
    [/^POST \/api\/workspaces\/:workspaceId\/feishu\/messages\/:messageId\/draft-reply$/, "feishu.messages.draft-reply"],
    [/^POST \/api\/workspaces\/:workspaceId\/feishu\/messages\/:messageId\/propose-issue$/, "feishu.messages.propose-issue"],
    [/^POST \/api\/workspaces\/:workspaceId\/feishu\/messages\/:messageId\/create-issue$/, "feishu.messages.create-issue"],
    [/^POST \/api\/workspaces\/:workspaceId\/feishu\/proposals\/:proposalId\/approve$/, "feishu.proposals.approve"],
    [/^POST \/api\/workspaces\/:workspaceId\/feishu\/proposals\/:proposalId\/reject$/, "feishu.proposals.reject"],
    [/^GET \/api\/issues\/:id\/change-requests$/, "scm.change-request.list"],
    [/^PUT \/api\/issues\/:issueId\/change-requests\/:changeRequestId$/, "scm.change-request.link"],
    [/^DELETE \/api\/issues\/:issueId\/change-requests\/:changeRequestId$/, "scm.change-request.unlink"],
    [/^POST \/api\/(?:multiremi\/)?inbox\/:id\/read$/, "inbox.read"],
    [/^POST \/api\/(?:multiremi\/)?inbox\/:id\/archive$/, "inbox.archive"],
    [/^DELETE \/api\/(?:multiremi\/)?pins\/:itemType\/:itemId$/, "pin.delete"],
    [/^GET \/api\/remi\/releases\/latest\/:filename$/, "platform.release.latest"],
    [/^GET \/api\/remi\/releases\/download\/:tag\/:filename$/, "platform.release.get"],
    [/^GET \/api\/cloud-billing\/checkout-sessions\/:sessionId$/, "billing.checkout.get"],
    [/^GET \/api\/workspaces\/:id\/lark\/installations$/, "lark.installation.list"],
    [/^POST \/api\/workspaces\/:id\/lark\/install\/begin$/, "lark.install.begin"],
    [/^GET \/api\/workspaces\/:id\/lark\/install\/:sessionId\/status$/, "lark.install.status"],
    [/^DELETE \/api\/workspaces\/:id\/lark\/installations\/:installationId$/, "lark.installation.delete"],
  ];
  return rules.find(([pattern]) => pattern.test(route))?.[1] ?? null;
}

function exemptRoute(route: string): CliManifestRoute | null {
  const path = route.slice(route.indexOf(" ") + 1);
  const exempt = (category: CliExemptCategory, reason: string): CliManifestRoute => ({
    cli_exempt: true,
    category,
    reason,
  });
  if (path === "/ws" || path === "/api/daemon/ws" || path === "/api/realtime/ws") {
    return exempt("websocket_transport", "Long-lived WebSocket transport is outside the CLI command surface.");
  }
  if (path.startsWith("/api/daemon/") || /\/runtimes\/[^/]+\/heartbeat$/.test(path) || path === "/api/multiremi/scheduler/tick") {
    return exempt("daemon_internal_protocol", "Daemon heartbeat, claim, report, and execution protocol is machine-to-server traffic.");
  }
  if (path === "/api/multiremi/autopilots/:id/run-scheduled") {
    return exempt("daemon_internal_protocol", "Scheduler execution is machine-to-server traffic; users trigger an autopilot with remi autopilot run.");
  }
  if (path === "/api/multiremi/autopilots/:id/webhook") {
    return exempt("oauth_or_webhook_callback", "Autopilot webhook reception is invoked by an external system, not a user command.");
  }
  if (path === "/api/knowledge/events/repository-merged") {
    return exempt("daemon_internal_protocol", "SCM merge event ingestion is machine-to-server automation traffic; it is not a user command.");
  }
  if (path.startsWith("/api/webhooks/") || /\/(oauth|google|lark)\/callback$/.test(path)) {
    return exempt("oauth_or_webhook_callback", "External provider callback is authenticated and invoked by the provider, not a user command.");
  }
  if (path.startsWith("/api/platform-updater/")) {
    return exempt("platform_updater_internal", "Platform updater callback is an internal deployment control-plane protocol.");
  }
  if (path === "/api/cli/latest-version") {
    return exempt("platform_updater_internal", "Dashboard-only release discovery gates the CLI update control; CLI update workflows use runtime release commands.");
  }
  if (path === "/api/config" || path === "/api/contact-sales") {
    return exempt("pure_ui", "Browser bootstrap or presentation-only action has no meaningful CLI workflow.");
  }
  if (path === "/" || path === "/favicon.ico") {
    return exempt("public_bootstrap_asset", "Public service bootstrap asset has no user-side CLI operation.");
  }
  return null;
}

function plannedCommand(route: string): { domain: string; command: string } {
  const separator = route.indexOf(" ");
  const method = route.slice(0, separator);
  const path = route.slice(separator + 1);
  const segments = path.split("/").filter(Boolean);
  if (segments[0] === "api") segments.shift();
  if (segments[0] === "multiremi") segments.shift();
  let rawDomain = segments[0] ?? "platform";
  if (rawDomain === "workspaces" && segments.includes("scm")) rawDomain = "scm";
  else if (rawDomain === "workspaces" && segments.includes("feishu")) rawDomain = "feishu";
  else if (rawDomain === "issues" && segments.includes("change-requests")) rawDomain = "scm";
  else if (rawDomain === "workspaces" && segments.includes("lark")) rawDomain = "lark";
  else if (rawDomain === "workspaces" && segments.includes("session-archive")) rawDomain = "session";
  if (rawDomain === "auth") rawDomain = "context";
  if (rawDomain === "me") rawDomain = "member";
  if (rawDomain === "remi" || rawDomain === "install.sh") rawDomain = "platform";
  if (rawDomain === "cli-token") rawDomain = "token";
  if (rawDomain === "upload-file") rawDomain = "attachment";
  if (rawDomain === "lark") rawDomain = "lark";
  const domain = DOMAIN_ALIASES[rawDomain] ?? rawDomain;
  const staticTail = [...segments].reverse().find((segment) => !segment.startsWith(":")) ?? rawDomain;
  const collection = segments.length <= 1 || (segments.length === 2 && segments[1] === "search");
  let action = method === "GET" ? (collection ? "list" : "get")
    : method === "DELETE" ? "delete"
      : method === "PATCH" || method === "PUT" ? "update"
        : collection ? "create" : normalizeAction(staticTail);
  if (staticTail === "search") action = "search";
  if (path === "/health" || path === "/healthz" || path === "/readyz"
    || path === "/health/realtime" || path === "/api/multiremi/health") action = "status";
  if (staticTail === "archive" || staticTail === "restore" || staticTail === "verify" || staticTail === "retry"
    || staticTail === "cancel" || staticTail === "respond" || staticTail === "checkout" || staticTail === "trigger") {
    action = staticTail;
  }
  return { domain, command: `${domain}.${action}` };
}

function normalizeAction(value: string): string {
  return value.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "update";
}

main();
